### PR TITLE
Fix a bug with dyn_prep2.

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
Fix bug where icenmask was passed instead of iceemask. Also, change the ordering of some of the interpolations and halo updates.
- [X] Developer(s): 
dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
Ran the boxsyme test in CD and it compiles and runs 5 days.
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [X] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:
The boxsyme test now runs 5 days and looks good!

### CODE REVIEW

**Review by eclare108213 — COMMENTED** [review]
Changing the order of the halo updates etc might change the answers for B-grid.   Did you test that?  If not, please do.  If so, then I don't think you should make those changes if they are avoidable -- save it for later cleanup.  Just fix the 'n' vs 'e' errors.

**Comment by dabail10** [comment]
This will not change answers on the B grid. I only moved the CD-grid related interpolation and halo updates.

**Comment by apcraig** [comment]
I'm running the gridsys_suite tests now to confirm B is unchanged and check results of all CD tests.  Will have results soon and then will merge.  Will followup after merge with a full suite on cheyenne.

**Review by eclare108213 — APPROVED** [review]
I see.  The file differences are showing the HaloUpdate calls moved, but actually you moved the CD stuff around them.  Looks like now the warning check could be moved also and the `if (grid_ice == CD)` blocks combined.  But it's fine as it is, for now.

**Comment by apcraig** [comment]
The gridsys_suite results are here, https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#3bf12b835646d997c33462ed0de2fe57b6b5a6d2.  B answers are bit-for-bit, CD answers changed, but the islands tests are all still failing to complete according to the suite.  I'll merge and then run a full test suite just to be sure.

**Comment by dabail10** [comment]
The restart tests are still going to fail for the CD grid. I am working on that. Also, some debug tests are failing because of diagnostic print issues. This is mostly for "Antarctic" values in the box cases. I'll also work on a fix for this.

**Comment by apcraig** [comment]
Thanks @dabail10.  I agree the CD restart tests will fail.  For the islands tests, the B cases run fine, the CD cases do not in the gridsys_suite.  If the tests in that suite are not correct, we can change them, but something else is going on.  Are you sure you're testing the standard islands test?  For

cheyenne_gnu_smoke_gbox80_4x1_boxsyme_gridcd_kmtislands

I see

 (abort_ice)ABORTED: 
 (abort_ice) error = (ice_write_hist)ERROR: writing variable uvelE_1

in the output, for instance.

**Comment by dabail10** [comment]
Aha. I had not tried running kmtislands. I was thinking of the standard box tests. I will debug this one as well.

**Pull request merged**
