### PR TITLE
New deformationsC_T subroutine for more consistent calculation

### PR DESCRIPTION
**Pull request by JFLemieux73**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [x] Short (1 sentence) summary of your PR: 
    deformationsC_T uses DeltaT consistent with the rest of the C grid code. I have kept the previous approach (renamed deformationsCD_T) for the CD grid. This will need to be revisited later. 
- [x] Developer(s): 
@JFLemieux73 
- [x] Suggest PR reviewers from list in the column to the right.
  @apcraig 
- [x] Please copy the PR test results link or provide a summary of testing completed below.
    I tested one day gx3 run: BFB for B grid evp. It slightly changes the answer for the C grid (as expected).
- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [x] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [x] No, does the documentation need to be updated at a later time?
        - [x] Yes
        - [ ] No 
- [x] Please provide any additional information or relevant details below:

### CODE REVIEW

**Review by apcraig — COMMENTED** [review]
Is shearU halo updated before being used in deformationsC_T?
Have you checked bit-for-bit with different block sizes/pes?

**Comment by JFLemieux73** [comment]
The halo update for shearU is done just before the call for stressC_T. It is not recalculated after that and just passed to deformationsC_T. My original run was gx3 -p 8x1. I just did gx3 -p 1x1. Results are BFB.

**Review by apcraig — APPROVED** [review]

**Comment by apcraig** [comment]
Do you want me to merge now or wait for other feedback?

**Review by eclare108213 — COMMENTED** [review]
I don't understand what's happening here -- the subtleties need to be documented in code comments at the very least.  A potentially bigger concern (and maybe this is an issue in other places too) is the difference between averaging squares and squaring an average.  They aren't the same thing and can be VERY different when the elements being summed (before squaring) can take either positive or negative or negative values.  E.g. if a=2, b=3, then the average of squares is 6.5 and the square of the average is 6.25.  If a=2, b=-1, then those are 2.0 and 0.25.  Am I missing an assumption here?

**Review by dabail10 — APPROVED** [review]

**Comment by JFLemieux73** [comment]
This averages of the square was proposed by Bouillon et al. 2013 (eq. 11). It is also used by Kimmritz et al. 2016 (p. 61). 

Bouillon et al. 2013 mention:
"Apart from this averaging method, the spatial discretization is
the same as that presented in Bouillon et al. (2009). This change
ensures that the discretized equations satisfy the dissipative properties
of the VP model but does not lead to noticeable changes in
the results."

When I discussed with Martin Losch a few weeks ago, he mentioned that this averaging approach is important and recommended to use it. 

I think in our first C grid implementation we should follow a conservative approach. We should do what is in the literature. Later we could revisit these methods and improve them.

**Comment by JFLemieux73** [comment]
The references for the Bouillon and Kimmritz papers are already given as comments in the code. There is already the following comment in stressC_T:

!-----------------------------------------------------------------
! Square of shear strain rate at T obtained from interpolation of
! U point values (Bouillon et al., 2013, Kimmritz et al., 2016
!-----------------------------------------------------------------

Should I add this in deformationsC_T?

**Comment by JFLemieux73** [comment]
I would like to add one last thing. In Bouillon et al. 2013 and in Kimmritz et al. 2016, the average of the squares is used to calculate Delta at the T point in order to calculate the viscosities and replacement pressure. 

Both models are however single-category models so there is not issue of using DeltaT for ridging/redistribution.

In our case, however, DeltaT is used in the deformations subroutines to calculate deformations for ridging/redistribution. The change in this PR is to make consistent DeltaT for viscosities (and replacement pressure) and the DeltaT in the deformationsC_T subroutine.

**Review by eclare108213 — APPROVED** [review]
Okay, it sounds like you've considered this carefully and I'm just behind the learning curve.  If there's a way to make this approach explicit in the documentation's equations, please do, when you get to that.  Thanks!

**Pull request merged**
