### PR TITLE
Implement support for grid_ice = "C" and add bigblock and gauss ICs.

### PR DESCRIPTION
**Pull request by apcraig**
This adds support for grid_ice = "C" which is bit-for-bit with "CD" as initial default.

Add support for ice_data_type = "bigblock" and "gauss".  Both cover 90% of the domain with ice, avoiding the edges of the domain.  bigblock is a constant depth block of ice.  gauss is a gaussian distribution of ice.

To use "gauss", for example, create a boxsyme case with gbox80 (./cice.setup -m cheyenne -e intel -p 1x1x80x80x1 --test smoke -s boxsyme,diag1,gridcd --testid tB02 -g gbox80)  then manually change ice_data_type in namelist to "gauss".

### CODE REVIEW

**Review by JFLemieux73 — APPROVED** [review]
That's great Tony! Thanks a lot. Everything looks ok.

**Review by dabail10 — APPROVED** [review]

**Review by phil-blain — COMMENTED** [review]
I had a quick look and did not find anything that caught my eye. Thanks!

**Review by eclare108213 — APPROVED** [review]
Just to clarify, in this PR the 'C' and 'CD' options are functionally identical, because nothing has been added yet to differentiate them?

**Comment by apcraig** [comment]
@eclare108213, that is correct.  Moving forward, we'll need to modify the C grid implementation so it produces a different and correct C-grid solution.  Originally, I had modifications to everything but the dynamics and choosing "C" led to aborts because the dynamics weren't doing anything/enough.  I ended up just setting "C" = "CD" in the dynamics so it would run to completion and I could confirm bit-for-bit with "CD".  It's a starting point.

**Comment by apcraig** [comment]
Will merge when GHActions is done.

**Pull request merged**
