### PR TITLE
Initialize uvel, vvel at every substep

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
Added lines to initialize U grid velocities at beginning at substep.
- [X] Developer(s): 
dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
Builds and runs with grid_system = 'CD'. Still blows up in box_islands case.
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [X] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:
This will change answers as uvel/vvel are used in stress_U and were not updated.

### CODE REVIEW

**Review by eclare108213 — APPROVED** [review]
I don't immediately understand why this needs to be done at the beginning of every subcycle.  If the dynamics solution is being computed on the CD grid, shouldn't the velocities already be in the right location during the calculation?  Is this because the stresses are computed in multiple locations and therefore need velocities in multiple locations?  I'll approve, assuming that's the case.

Note:  this might be better done with a 4-point average rather than a 2-point average, for stability.

**Comment by dabail10** [comment]
Maybe a four point average is better here. The U-point velocities are needed for the strain rate equations here. However, perhaps we should just do this locally in strain_rates_U and do the four point average.

 ! MIGHT NOT NEED TO mult by uvm...if done before in calc of uvelU...
      
      ! divergence  =  e_11 + e_22
      divU     = dyU(i,j) * ( uNip1j - uNij ) &
               + uvelU(i,j) * uvm(i,j) * ( dyN(i+1,j) - dyN(i,j) ) &
               + dxU(i,j) * ( vEijp1 - vEij ) &
               + vvelU(i,j) * uvm(i,j) * ( dxE(i,j+1) - dxE(i,j) )

      ! tension strain rate  =  e_11 - e_22
      tensionU = dyU(i,j) * ( uNip1j - uNij ) &
               - uvelU(i,j) * uvm(i,j) * ( dyN(i+1,j) - dyN(i,j) ) &
               - dxU(i,j) * ( vEijp1 - vEij ) &
               + vvelU(i,j) * uvm(i,j) * ( dxE(i,j+1) - dxE(i,j) )

**Comment by JFLemieux73** [comment]
Good catch Dave! Yes we do need it at the beginning of every subcycle.

**Comment by apcraig** [comment]
It's merged.  Feel free to grab the update off the branch.

**Pull request merged**
