### PR TITLE
Add gbox12 and ice_data_type='smallblock'

### PR DESCRIPTION
**Pull request by apcraig**
Add gbox12 and ice_data_type='smallblock'.

Tested quickly on cheyenne, seems to be OK.

## PR checklist
- [ ] Short (1 sentence) summary of your PR: 
    ENTER INFORMATION HERE
- [ ] Developer(s): 
    ENTER INFORMATION HERE
- [ ] Suggest PR reviewers from list in the column to the right.
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
    ENTER INFORMATION HERE 
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:

### CODE REVIEW

**Review by eclare108213 — APPROVED** [review]
Looks fine to me, although @JFLemieux73 might prefer a different atm forcing.

**Comment by apcraig** [comment]
You have to set 'smallblock' manually anyway because of how boxsym is setup.  So you can just manually change the atm_data_type if needed too.  I think one of the cleanup tasks is to review the atm/ocn/ice_data_type settings for a few of the box test options.

**Review by dabail10 — APPROVED** [review]

**Comment by JFLemieux73** [comment]
Thanks @apcraig. Yes I think it would be better to have atm_data_type = 'uniform_east'

**Comment by apcraig** [comment]
@JFLemieux73, it doesn't actually matter what we set in gbox12.  If you want boxsyme, then you'll have to choose boxsyme too.  But then you'll have to manually set ice_data_type to 'smallblock' because boxsyme will override the gbox12 default.  On the other hand, if you use gbox12 without boxsyme and we set the atm_data_type in gbox12 to 'uniform_east', then you'll get 'smallblock'  and 'uniform_east', but you won't get any of the other boxsyme settings, like thermodynamics off and so forth.  The box settings need some changes to support the different configurations we want.  What I think I'll do is set the gbox12 ice_data_type setting to 'box2001' to be consistent with gbox80.  Then you can manually change any of the box cases to ice_data_type='smallblock' if that's the initial ice condition you want to run.

**Review by JFLemieux73 — APPROVED** [review]

**Pull request merged**
