### PR TITLE
ice_dyn_shared: add 'viscous_coeffs_and_rep_pressure_T' subroutine

### PR DESCRIPTION
**Pull request by phil-blain**
Add a subroutine mimicking what 'viscous_coeffs_and_rep_pressure' does,
but at a single location.

Name it '*_T' since it's going to be used to compute the viscous
coefficients and replacement pressure at the T point.

### CODE REVIEW

**Comment by apcraig** [comment]
Looks like this fails to compile in github actions.  @phil-blain, can you take a look.

**Comment by phil-blain** [comment]
Yeah - it's actually JF's commit which makes the build fail. I'll let him fix that (I guess tomorrow), then I'll rebase my branch.

**Comment by apcraig** [comment]
I merged a fix to cgridDEV, but the checks on this PR still fail.  I wonder why github doesn't merge this PR to the current branch being merged to.  I restarted github actions manually, and it still fails with the old error.  So I guess the fix has to be merged onto this branch.

**Comment by apcraig** [comment]
I tested this offline last night and it seems fine.  all still bit-for-bit.

**Pull request merged**
