### PR TITLE
Cgrid debug

### PR DESCRIPTION
**Pull request by TillRasmussen**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [ ] Short (1 sentence) summary of your PR: 
    Fix bug that make CD grid finalize runs within quicksuite. Initialize zetax2T and etax2T
- [ ] Developer(s): 
    Till Rasmussen
- [ ] Suggest PR reviewers from list in the column to the right.@apcraig @JFLemieux73 @eclare108213
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
    ENTER INFORMATION HERE 
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [ x] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [x ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [ x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:
  zeta

### CODE REVIEW

**Comment by TillRasmussen** [comment]
Initializing zetax2T and etax2T avoid spurious values when they are used.This is a cure but maybe only for the  immediate symptoms.
The reason is most likely the different masks used for T and u. When averaged to U points this causes numerical issues as not calculated T points are used despite that the mask is used.

**Comment by apcraig** [comment]
The averaging across different masks is something we made need to extend.  The underlying masks used are tmask, umask, nmask, emask for the "S" averaging.  It could be that we need some other averagers that, for instance, send in the mask and/or weight as part of the call.  We should review all the average calls in the CD implementation and make sure we understand what is needed vs what is currently being done.

**Review by daveh150 — APPROVED** [review]
Looks good, this seems like a good practice to initialize to zero to avoid unexpected results. Perhaps in FORTRAN it does not automatically initialize allocable arrays to zero?

**Comment by apcraig** [comment]
There are pluses and minuses to this approach.  By setting arrays to zero, you allow the code to run to completion.  But I think that something is still probably wrong.  A value is not being computed somewhere where maybe it should.  If initializing to zero is "correct", then that's great.  If it's covering up another problem, then the benefit of this fix is mixed.

It would be good to understand better whether the masked computations are all correct, and what may need to change to fix this properly.

**Comment by TillRasmussen** [comment]
@apcraig is right this hides the fact that the icepoints with the T mask is a subset of the umask due to the fact that umask assigns icepoints to places where the four neighboring points can include up to two landpoint. Tmask requires that all points are ocean and have some ice. Despite that the mask captures these by multiplication there are some places where the absolute value is very small or big and sometimes NaN. The question is then if c0. is a good "missing value" value for the viscous coefficients.

**Comment by eclare108213** [comment]
What's the status of this PR?  Should it be merged as-is, or is there some uncertainty about whether this is the right thing to do?

**Comment by apcraig** [comment]
I'm waiting on some consensus about whether this should be merged or not.  I'm happy to go either way.

**Review by apcraig — APPROVED** [review]

**Review by dabail10 — APPROVED** [review]

**Pull request merged**
