### PR TITLE
Added comments: ref of Bouillon 2009, 2013, Hunke 2002 and Kimmritz 2016

### PR DESCRIPTION
**Pull request by JFLemieux73**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- Added references to the papers used for the C grid discretization
    ENTER INFORMATION HERE
- [ ] Developer(s): 
    ENTER INFORMATION HERE
- [ ] Suggest PR reviewers from list in the column to the right.
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
    ENTER INFORMATION HERE 
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:

### CODE REVIEW

**Comment by apcraig** [comment]
These references probably should be added to the formal documentation bibliography if they're not there already.  I guess could be done when the documentation is updated.

**Comment by JFLemieux73** [comment]
Yes I will do it later. I noted it in issue #651. Looks like I have some work to do for the documentation...

**Review by dabail10 — APPROVED** [review]
This looks good. I can make sure these get added to the documentation as well.

**Review by apcraig — APPROVED** [review]

**Comment by apcraig** [comment]
I got the conflicts resolved finally.

**Pull request merged**
