### PR TITLE
Add stress terms to history for N and E grids.

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
 Add stress terms to history for N and E grids. Also, use capital N and E in uvel and vvel.
- [X] Developer(s): 
 dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
quick_suite:
16 measured results of 16 total results
16 of 16 tests PASSED
0 of 16 tests PENDING
0 of 16 tests MISSING data
0 of 16 tests FAILED
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [X] Yes
        - [ ] No 
- [X] Please provide any additional information or relevant details below:

### CODE REVIEW

**Comment by apcraig** [comment]
I merged a fix to cgridDEV, but the checks on this PR still fail.  I wonder why github doesn't merge this PR to the current branch being merged to.  I restarted github actions manually, and it still fails with the old error.  So I guess the fix has to be merged onto this branch.

**Comment by apcraig** [comment]
Lots of things are failing when I test.  @dabail10, could you run at least the quick_suite with a few compilers and see if you can fix the errors.  Once you think it's working, I can run the base_suite again and check for bfb regression.  thanks.

**Comment by dabail10** [comment]
Fixed this and it ran successfully through the quick_suite.

**Comment by apcraig** [comment]
I ran a full suite last night on cheyenne with this code and everything passed and is bit-for-bit.

**Pull request merged**
