### PR TITLE
Just add stress terms to history.

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [ ] Short (1 sentence) summary of your PR: 
    ENTER INFORMATION HERE
- [ ] Developer(s): 
    ENTER INFORMATION HERE
- [ ] Suggest PR reviewers from list in the column to the right.
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
    ENTER INFORMATION HERE 
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:

### CODE REVIEW

**Comment by dabail10** [comment]
I think this is failing because of the call to principal_stress. I had not run this in debug mode.

**Comment by apcraig** [comment]
This fails GithubActions, seems it is not running correctly with the B case.  It is seg faulting with a memory error.

For many other C fields, we have a history namelist that turns on multiple fields.  For instance, f_uvel turns on uvel in B and uvel+uvelE in C.  Should we implement this in a similar way?  Maybe we have f_stressm, f_stressp, f_stress12 and then the appropriate variables are turned on depending on the grid?

**Comment by apcraig** [comment]
I might even advocate just having f_stress and then that turns on all the appropriate variables?

**Comment by dabail10** [comment]
Aha. Yes, I set these to be on all the time.

**Comment by dabail10** [comment]
Probably a good idea.

**Comment by apcraig** [comment]
We're close to merging back to master.  We want to minimize last minute fixes at this point and I fear once we merge this, we'll be stuck with the implementation choice.  I'm not saying the implementation needs to change, but if we want it to be implemented a little differently (as suggested above), then I think we should do that now.

**Comment by dabail10** [comment]
That is fine. I am just putting this here to @JFLemieux73 can try it out.

**Comment by apcraig** [comment]
So this PR should not be merged at this time?

**Comment by dabail10** [comment]
Let's hold off on it.

**Comment by apcraig** [comment]
I am going to close this PR.

**Pull request closed without merging**
