### PR TITLE
Added boxnodyn tests to gridsys_suite.ts. Also added machinery to sub…

### PR DESCRIPTION
**Pull request by daveh150**
…mit batch jobs on local NRLSSC grid system

For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [ ] Short (1 sentence) summary of your PR: 
   Added boxnodyn to gridsys_suite.ts. Also added options to run on local NRLSSC grid cluster.
- [ ] Developer(s): 
  David Hebert
- [ ] Suggest PR reviewers from list in the column to the right.
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
    ENTER INFORMATION HERE 
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [ X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X ] No 
- [ ] Please provide any additional information or relevant details below:

### CODE REVIEW

**Comment by daveh150** [comment]
The boxnodyn test passed (I have not looked at output to be honest). This test failed, I can't tell why:

NRLSSC_gnu_restart_gx3_4x2_debug_diag1_gridcd

Does this fail for you when you run the gridsys_suite?

**Comment by apcraig** [comment]
This looks fine to me @daveh150.  Your result for NRLSSC_gnu_restart_gx3_4x2_debug_diag1_gridcd is correct.  The case runs to completion fine (the "run" passes), but the exact restart fails which is expected.  We haven't started to debug exact restart of CD.  Your output should look like

PASS NRLSSC_gnu_restart_gx3_4x2_debug_diag1_gridcd run
FAIL NRLSSC_gnu_restart_gx3_4x2_debug_diag1_gridcd test

which means the run completed, but the exact restart "test" failed.

**Review by apcraig — COMMENTED** [review]
Could we change the machine name to nrlssc (lower case) to be consistent with all the other machine names?

**Review by eclare108213 — APPROVED** [review]
In your boxnodyn tests, are the velocity components identically zero?

**Comment by daveh150** [comment]
Changed institution to lowercase nrlssc. 

I confirm in my tests the boxnodyn cases have zero velocities for both the B and CD tests.

**Review by apcraig — APPROVED** [review]

**Pull request merged**
