### PR TITLE
New subroutines for rheology calc for CD grid

### PR DESCRIPTION
**Pull request by JFLemieux73**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [x] Short (1 sentence) summary of your PR: 
    New subroutines: stress_T, deformations_T and viscous_coeff_and_rep_pressure_T
- [x] Developer(s): 
   @JFLemieux73 
- [x] Suggest PR reviewers from list in the column to the right. 
@eclare108213 
- [x] Please copy the PR test results link or provide a summary of testing completed below.
   compiles, smoke test works fine.
- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [x] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [x] No, does the documentation need to be updated at a later time?
        - [x] Yes
        - [ ] No 
- [x] Please provide any additional information or relevant details below:

### CODE REVIEW

**Comment by apcraig** [comment]
Please check diffs to make sure they look OK.  It seems that viscous_coeffs_and_rep_pressure_T is being added again.  Maybe you added the same code to your branch as @phil-blain PRed and maybe the merge will be fine, but we don't want to end up with two of the same methods in the same file.  The PR says it can be merged without conflict.  Thoughts?

**Comment by apcraig** [comment]
github actions is failing because there is an extra viscous_coeffs_and_rep_pressure_T.

**Comment by JFLemieux73** [comment]
I can't connect to zoom...it says the meeting has not started. Could you please check what's wrong?

**Comment by dabail10** [comment]
Just reconnected.

**Comment by phil-blain** [comment]
we'll close this one and JF will open a new one.

**Comment by phil-blain** [comment]
superseded by https://github.com/apcraig/CICE/pull/10

**Pull request closed without merging**
