### PR TITLE
review comments

### PR DESCRIPTION
**Pull request by anton-seaice**

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
For the UFS side, I think the original placement of the code block in ice_comp_nuopc inside the CESMCOUPLED ifdef would also work, at least for how we intend to use these pio options at this point (via namelist). I think it does no harm (other than generating a warning message) where it is now, but I'm also fine if you revert to the original placement. 

One question...the code includes the comment

```
! The only reason to set these is to detect in ice_history_write if the chunk/deflate settings are ok.
```

To me, this implies that the same type of checking might not happen if the pio options are set via namelist?

**Comment by anton-seaice** [comment]
> For the UFS side, I think the original placement of the code block in ice_comp_nuopc inside the CESMCOUPLED ifdef would also work, at least for how we intend to use these pio options at this point (via namelist). I think it does no harm (other than generating a warning message) where it is now, but I'm also fine if you revert to the original placement.
> 

Ah - I didn't think this through. It is in the right place without this PR. 

- If CESMCOUPLED is set, then the iotype comes through NUOPC & CESM shared routines and we need to set the namelist `_format` options in the driver.
- If CESMCOUPLED is not set, then format comes through the namelist and is handled in ice_init in the same way as the standalone configuration.

> One question...the code includes the comment
> 
> ```
> ! The only reason to set these is to detect in ice_history_write if the chunk/deflate settings are ok.
> ```
> 
> To me, this implies that the same type of checking might not happen if the pio options are set via namelist?

Its about lines like [this](https://github.com/CICE-Consortium/CICE/pull/928/files#diff-55c90d35b6358ae6258cfdd0c15555a9bd5761941811e02ad68a95e08a3acbbfR933):

```
if (restart_format=='hdf5' .and. restart_deflate/=0) then
         status = pio_def_var_deflate(File, vardesc, shuffle=0, deflate=1, deflate_level=restart_deflate)
```

in `ice_history_write.F90` and `ice_restart.F90`. If the format is set in the namelist then that if statement works fine too. I will try and reword. Maybe something like 'CICE history and restart handling needs these set to enable chunking / deflate'

**Comment by apcraig** [comment]
@anton-seaice, please close or revise this PR as needed.  Let me know when it's ready.

**Comment by anton-seaice** [comment]
@DeniseWorthen , I assume the nuopc driver checks are ok without this change?

**Comment by DeniseWorthen** [comment]
@apcraig Yes, thanks. I've been testing w/o the change in ice_comp_nuopc.F90

**Pull request closed without merging**
